#ifndef DEFINITIONS_HPP
#define DEFINITIONS_HPP

#define AboutApp "My First Doctor is a health app which helps users to know about diseases, first aid, contacts, food tips and many other health related informations."

#define HealthTip1 " Early to bed and early to rise, makes a man healthy wealthy and wise."
#define HealthTip2 " Never skip a breakfast."
#define HealthTip3 " I think you probably brush twice a day."
#define HealthTip4 " A good laugh and a long sleep are the best cures for every sickness."
#define HealthTip5 " Health is a relationship between you and your body."
#define HealthTip6 " Health is not simply the absence of sickness."
#define HealthTip7 " Always wash hands before eating."
#define HealthTip8 " Get at least 30 minutes of exercise a day."
#define HealthTip9 " Dont drink or smoke."
#define HealthTip10 " Sleep with your lights off."
#define HealthTip11 " Smoking kills."
#define HealthTip12 " Sleep well everday."
#define HealthTip13 " Try minimizing sugar intake,its bad for health."
#define HealthTip14 " Drink more water."
#define HealthTip15 " Manage stress by being optimistic."
#define HealthTip16 " Worry less, say ALL IS WELL."
#define HealthTip17 " Have health checkups regularly."
#define HealthTip18 " Avoid processed junk foods."
#define HealthTip19 " A lack of exercise now causes as many deaths as smoking."
#define HealthTip20 " Yoga can boost your cognitive function and lowers stress."
#define HealthTip21 " Stretching increases the blood flow to your muscles and helps avoid injuries."
#define HealthTip22 " Consuming water helps the body maintain its natural pH balance."
#define HealthTip23 " The blue light in phones can mess with your sleep rhythm."
#define HealthTip24 " Eggs are among the healthiest foods you can eat."
#define HealthTip25 " Never miss your child's vaccination."
#define HealthTip26 " Load up on vitamin C by eating at least five servings of fresh fruit and vegetables every day."
#define HealthTip27 " Folic acid found in green leafy vegetables can play a role in cancer prevention."
#define HealthTip28 " A for Away. This vitamin, and beta carotene, help to boost immunity against disease."
#define HealthTip29 " Don’t have soft drinks or energy drinks while you're exercising."
#define HealthTip30 " Carbohydrates will give instant energy and accelerate your metabolism."
#define HealthTip31 " Breathe deeply to help your body move oxygen-rich blood to those sore muscles."
#define HealthTip32 " Never bounce or force yourself into an uncomfortable position."
#define HealthTip33 " Not only should you alternate your routine to prevent burnout or boredom, but to give your body a jolt. "
#define HealthTip34 " Increase your bouts of speed in small increments."
#define HealthTip35 " You need to know if there are any inherited diseases prowling your gene pool."
#define HealthTip36 " Beat the sneezes. There are more than 240 allergens, some rare and others very common."
#define HealthTip37 " Swimming is the most asthma-friendly sport of all."
#define HealthTip38 " Sun rays can burn even through thick glass, and under water."
#define HealthTip39 " 50% of UVB rays and 75% of UVA rays penetrate a meter of water and wet cotton clothing. "
#define HealthTip40 " Coconut lotions contain psoralen, which speeds up the ageing process."
#define HealthTip41 " Laugh and cry. Having a good sob is reputed to be good for you."
#define HealthTip42 " Laughter, which has been shown to help heal bodies, as well as broken hearts."
#define HealthTip43 " Laughter boosts the immune system and helps the body shake off allergic reactions."
#define HealthTip44 " End relationships that no longer work for you, as you could be spending time in a dead end."
#define HealthTip45 " Strong people go for help. Ask for assistance."
#define HealthTip46 " Showering or bathing in water that too hot will dry out your skin and cause it to age prematurely."
#define HealthTip47 " Adding a little olive oil to your bath with help keep your skin moisturised."
#define HealthTip48 " Diabetes is often part of a metabolic syndrome, which includes high B.P. and other risk factors for heart disease."
#define HealthTip49 " Eat more fruits and veggies."
#define HealthTip50 " Eat Eggs, and Dont throw away the Yolk."
#define HealthTip51 " Added sugar is the single worst ingredient in the modern diet."
#define HealthTip52 " Take Vitamin D3 If You Do not Get Much Sun."
#define HealthTip53 " Avoid bright lights before sleep specially blue light."
#define HealthTip54 " Despite being high in fat, nuts are incredibly nutritious and healthy."
#define HealthTip55 " Sugary drinks are the most fattening things you can put into your body."
#define HealthTip56 " Rest heals the body and lessens the risk of heart trouble and psychological problems."
#define HealthTip57 " More than 80% of type 2 diabetics die of heart disease. "
#define HealthTip58 " Eat well, Sleep well, You will do well."
#define HealthTip59 " Avoid junk foods."
#define HealthTip60 " Drink more water."

#define ParkinsonsTips "1.Avoid taking sugar.\n2.Drink a lot of water.\n3.Eat food with low cholestrol.\n4.Do exercises and stretches."
#define MeningitisTips "1.Get vaccinated.\n2.Avoid sharing belongings of infected person.\n3.Eat nutritional diets.\n4.Improve immune functions."
#define EncephalitisTips "1.Stay away from light.\n2.Rest well.\n3.Visit doctor on a daily basis.\n4.Eat lots of protein containing foods."
#define AlzeimerTips "1.Try to reduce stress.\n2.Have a flexible routine.\n3.Eat healthy, be happy.\n4.Drink plenty of water."
#define ClusterHeadacheTips "1.Be social, make friends, to enjoy and be tension free.\n2.Avoid fast foods and junk foods.\n3.Taking short naps could be helpful.\n4.Take breaks often.\n"
#define TensionHeadacheTips "1.Sleep 6-8 hours daily.\n2.Relax, Meditate, breathe deeply.\n3.Dont involve in too many matters.\n4.Share your problems with your family.\n"
#define MigraineTips "1.Stay away from bright light.\n2.Close your eyes and rest.\n3.Massage your neck and temples.\n4.Avoid noisy environments.\n"
#define SinusHeadacheTips "1.Keep the body hydrated.\n2.Rest well.\n3.Flush your nasal passages.\n4.Take a steam bath.\n"
#define CataractTips "1.Check eye frequently when you are 40+.\n2.If blured vision is observed, imediately rush to hospital.\n3.Avoid fatty foods.\n4.Be consious about Cataract, if you have family history of having Cataract.\n"
#define ConjunctivitisTips "1.Wear thick glasses to prevent transmission.\n2.Dont stare into red eyes.\n3.Avoid touching or rubbing your eyes. This can worsen the condition or spread it to your other eye.\n4.Do not share personal items, such as pillows, towels,  eye or face makeup, makeup brushes, or eyeglasses."
#define DryEyeSyndromeTips "1.Wash your hands often with soap and warm water.\n2.Do not rub or touch your eyes often.\n3.Stop wearing contact lenses until your eye doctor says.\n4.Use special droppers to moisturize eyes, if it feels dry.\n"
#define GlaucomaTips "1.Eat a Variety of Healthy, Nutrient-dense Foo\n2.Maintain a Healthy Weight.\n3.Keep Blood Pressure at a Normal Level.\n4.Quit Smoking."
#define GingivitisTips "1.Brush twice a day.\n2.Quit Smoking.\n3.Intake more calcium in diet.\n4.Have regular dental checkups."
#define DecayTips "1.Brush Twice a day regularly.\n2.Make regular dental visits.\n3.Lower the sugar intake.\n4.Limit the acidic foods."
#define PeriodontalTips "1.Get regularly dental cleaning.\n2.Quit Smoking.\n3.Brush twice a day.\n4.Use toothpaste containing flouride."
#define SensitivityTips "1.Limit the acidic foods.\n2.Avoid too hot or too cold foods.\n3.Use desensitizing toothpaste.\n4.Have regular dental checkups."
#define CardiomypathyTips "1.Exercise daily.\n2.Maintain your body weight and cholestrol.\n3.Avoid taking too much of stress.\n4.Prevent blood clots."
#define MyocardialInfarctionTips "1.Maintain Blood Pressure and Cholestrol level.\n2.Exercise regularly.\n3.Avoid too much of stress.\n4.Maintain healthy body weight."
#define CoronaryHeartDiseaseTips "1.Exercise regularly.\n2.Quit Alcohol and Smoking.\n3.Maintain healthy body weight and cholestrol level.\n4.Avoid stress and be happy."
#define CongenitalHeartDiseaseTips "1.Get genetic counseling before the birth of children.\n2.Make sure to know about family disease.\n3.Limit unhealthy fats in diets.\n4.Exercise on daily basis."
#define TuberculosisTips "1.Do not share personal items.\n2.Never sleep in dark rooms.\n3.Take enough rest.\n4.Avoid too crowdy places."
#define PneumoniaTips "1.Avoid Smoking.\n2.Incase of extreme pain, rush to hospital.\n3.Eat healthy and fresh foods.\n4.Avoid making contact with sick people."
#define COPDTips "1.Try to adjust change in weather.\n2.Take enough sleep.\n3.Avoid sharing personal items such as pencil, towel.\n4.Avoid eating junk foods."
#define AsthmaTips "1.Know about family history of your family of having asthma.\n2.If the age is above 40,then regulara check up.\n3.Avoid coughing too much.\n4.Sleep well."
#define AppendicitisTips "1.Avoid foods which are too hard to digest.\n2.Take lots of rest.\n3.Avoid eating too much meat.\n4.Eat foods with lots of fibers."
#define CholeraTips "1.Drink plenty of fluids.\n2.Avoid anti vomitinng medications.\n3.Always keep your kitchen clean.\n4. Use boiled or purified water."
#define JaundiceTips "1.Drink at least eight glasses of fluids per day.\n2.Eat foods which are rich in digestive enzymes.\n3.Eat lots of vegetables and fruits.\n 4.Look for high-fiber foods, such as oatmeal, berries, and almonds."
#define HepatitisBTips "1.Get vaccinated.\n2.Eat a healthy diet of fruit, whole grains.\n3.Avoid eating raw or undercooked foods.\n4.Reduce your stress levels. "
#define UremiaTips "1.Control diabetes by controlling level of sugar.\n2.Maintain a healthy blood pressure.\n3.Maintain cardiovascular health\n4.Quit smoking"
#define KidneyStoneTips "1.Drink a lot of water.\n2.Cut back on salt in your diet.\n3.Limit the amount of animal proteins you consume.\n4.Reduce your intake of oxalate-rich foods."
#define KidneyCancerTips "1.Don’t smoke.\n2.Maintain a healthy body weight.\n3.Find out if you’re exposed to certain toxins at work or at home.\n4.Control high blood pressure."
#define KidneyInjuryTips "1.Drink plenty of water a day.\n2.Cut back on salt in your diet.\n3.Limit the amount of animal proteins you consume.\n4.Limit the amount of calcium."

#endif // DEFINITIONS_HPP
